baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://alextsui05.github.io" # the base hostname & protocol for your site
title: "alextsui05.github.io"
paginate: 3

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."
description:         'CS grad @ UC Davis who wishes to have nice things in C++, Python, Bash, C# and so, writes them.'

gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "_posts/2014-06-28-example-bootstrap.md"
  - "_posts/2014-07-27-exmaple-css.md"
  - "_posts/2014-07-28-introducing-shiori.md"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
