baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://atsui.me" # the base hostname & protocol for your site
title: "atsui"
paginate: 3

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."
description:         'Computer science grad student at UC Davis, writes C++, enjoys learning languages, and occasionally video games.'

gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "_posts/2014-06-28-example-bootstrap.md"
  - "_posts/2014-07-27-exmaple-css.md"
  - "_posts/2014-07-28-introducing-shiori.md"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
