url: 'https://alextsui05.github.io'
baseurl: 'jekyllwind-test'
title: 'Jekyllwind'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
