baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Alex Tsui'
description = 'Read, Write, Repeat'
sectionPagesMenu = 'main'

# https://github.com/theNewDynamic/gohugo-theme-ananke/wiki/Installation-as-GoHugo-Module
[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[params.ananke.social.follow]
networks = [
  'facebook',
  'github',
  'x-twitter'
]

[params.ananke.social.facebook]
username = 'tsui.a'

[params.ananke.social.github]
username = 'alextsui05'

[params.ananke.social.x-twitter]
username = 'alextsui'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
